name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [ periodic ]

jobs:
  build:
    runs-on: ${{ matrix.config.image }}
    strategy:
      matrix:
        config:
          - image: macos-12
            shortName: macos
          - image: ubuntu-22.04
            shortName: linux
          - image: windows-2022
            shortName: windows
      fail-fast: false
    steps:
      - name: Check out the sources
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'sbt'

      - name: Build
        run: sbt compile

      - name: Test
        run: sbt test

      - name: Package
        run: sbt universal:packageBin

      - name: Upload package result
        uses: actions/upload-artifact@v4
        with:
          name: checktimer.${{ matrix.config.shortName }}
          path: target/universal/*.zip

  release:
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: checktimer.linux
          path: ./target/package/linux/
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: checktimer.macos
          path: ./target/package/macos/
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: checktimer.windows
          path: ./target/package/windows/

      - name: Prepare the release notes
        uses: ForNeVeR/ChangelogAutomation.action@v1
        with:
          input: ./CHANGELOG.md
          output: ./release-notes.md
          format: Markdown
      - name: Upload the release notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: ./release-notes.md

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/package/linux/*.zip
            ./target/package/macos/*.zip
            ./target/package/windows/*.zip
          body_path: ./release-notes.md
