# SPDX-FileCopyrightText: 2024 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

name: Main
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [ periodic ]

jobs:
  build:
    strategy:
      matrix:
        config:
          - image: macos-12
            shortName: macos
          - image: ubuntu-22.04
            shortName: linux
          - image: windows-2022
            shortName: windows
      fail-fast: false
    runs-on: ${{ matrix.config.image }}
    name: build.${{ matrix.config.shortName }}
    steps:
      - name: Check out the sources
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'sbt'

      - name: Build
        run: sbt compile

      - name: Test
        run: sbt test

      - name: Package JVM
        run: sbt universal:packageBin

      - name: Build native
        if: matrix.config.shortName == 'windows'
        run: sbt universal:stage

      - name: Package native
        if: matrix.config.shortName == 'windows'
        shell: pwsh
        run: ./src/scripts/New-Package.ps1

      - name: Upload JVM package
        uses: actions/upload-artifact@v4
        with:
          name: checktimer.${{ matrix.config.shortName }}.jvm
          path: target/universal/*.zip

      - name: Upload native package
        if: matrix.config.shortName == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: checktimer.${{ matrix.config.shortName }}
          path: target/jpackage/checktimer

  licenses:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: REUSE license check
        uses: fsfe/reuse-action@v3

  release:
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
      - name: Check out the sources
        uses: actions/checkout@v4

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: checktimer.linux.jvm
          path: ./target/package/linux/
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: checktimer.macos.jvm
          path: ./target/package/macos/
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: checktimer.windows.jvm
          path: ./target/package/windows/
      - name: Download Windows package
        uses: actions/download-artifact@v4
        with:
          name: checktimer.windows
          path: ./target/native/windows/

      - name: Rename the packaged archives
        shell: bash
        run: |
          mv ./target/package/linux/*.zip ./target/package/linux/checktimer-linux.jvm.zip
          mv ./target/package/macos/*.zip ./target/package/macos/checktimer-macos.jvm.zip
          mv ./target/package/windows/*.zip ./target/package/windows/checktimer-windows.jvm.zip

      - name: Archive the Windows native package
        shell: pwsh
        run: Compress-Archive target/native/windows target/checktimer-windows.zip

      - name: Prepare the release notes
        uses: ForNeVeR/ChangelogAutomation.action@v1
        with:
          input: ./CHANGELOG.md
          output: ./release-notes.md
          format: Markdown
      - name: Upload the release notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: ./release-notes.md

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./target/package/linux/*.zip
            ./target/package/macos/*.zip
            ./target/package/windows/*.zip
            ./target/checktimer-windows.zip
          body_path: ./release-notes.md
